### ISSUE TITLE
this offset of MU_IIR and MU_IER is wrong , MU_IIR shoule 0x48 , MU_IER should 0x44

### ISSUE THREAD

**Issue by SaarloosJohn** [seL4/util_libs#120]
https://github.com/seL4/util_libs/blob/b0cedde66a6b5a3ef1bc072f9a08a4e6bd68935c/libplatsupport/src/plat/bcm2837/serial.c#L20

this offset of MU_IIR and MU_IER is wrong , MU_IIR shoule 0x48 , MU_IER should 0x44
https://www.raspberrypi.org/app/uploads/2012/02/BCM2835-ARM-Peripherals.pdf page 8

**Comment by kent-mcleod** [comment]
Fixed by https://github.com/seL4/util_libs/pull/124

**Comment by kent-mcleod** [comment]
Thanks @SaarloosJohn !
