### ISSUE TITLE
Consider disabling prqueue workflow

### ISSUE THREAD

**Issue by kent-mcleod** [seL4/util_libs#128]
This seems to be the only repository that uses the workflow and PRs aren't being merged as a queue so it's not apparently helpful.

**Comment by lsf37** [comment]
Yes, I agree. @seL4/committers is anybody using the prqueue bot for reviewing?

**Comment by yyshen** [comment]
> Yes, I agree. @seL4/committers is anybody using the prqueue bot for reviewing?

I am not  using it.

**Comment by axel-h** [comment]
Not sure. I look at the mails it sends from time to time. But so far the pending PRs can also be handled manually.

**Comment by kent-mcleod** [comment]
Ok, I disabled it manually.  If we decide we don't need it, we can eventually delete the file from the repository.
