### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by namtsui** [seL4/util_libs#150]
flycast uses libelf.

see: 
https://github.com/flyinghead/flycast/blob/master/core/deps/libelf/elf.cpp

In that file, it states that it is released under this license:
```
 * Australian Public Licence B (OZPLB)
 * 
 * Version 1-0
 * 
 * Copyright (c) 2004 University of New South Wales
 * 
 * All rights reserved. 
 * 
 * Developed by: Operating Systems and Distributed Systems Group (DiSy)
 *               University of New South Wales
 *               http://www.disy.cse.unsw.edu.au
 * 
 ```

- Is this the same project as the one hosted here at seL4/util_libs?
- Has it been relicensed from Australian Public Licence B to BSD 2-clause?

https://github.com/seL4/util_libs/blob/master/libelf/src/elf.c

```
/*
 * Copyright (c) 1999-2004 University of New South Wales
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */
```

**Comment by lsf37** [comment]
I don't know what project https://github.com/flyinghead/flycast/blob/master/core/deps/libelf/elf.cpp is, but I can confirm that our `libelf` has been relicensed from OZPLB to BSD-2-Clause at some point in the past.
