### ISSUE TITLE
incorrect free size in imx ltimer destroy

### ISSUE THREAD

**Issue by bennoleslie** [seL4/util_libs#53]
```
    imx_ltimer_t *imx_ltimer = data;
...
    ps_free(&imx_ltimer->ops.malloc_ops, sizeof(imx_ltimer), imx_ltimer);
```

I think this is freeing something of the wrong size. If I'm not mistaken `sizeof(imx_ltimer)` is the size of the pointer not the size of the struct. I think it should be either `sizeof(imx_ltimer_t)` or (preferably) `sizeof *imx_ltimer`.

**Comment by kent-mcleod** [comment]
You seem to be right.  I guess this still works because most of these end up calling free(ptr) in the implementation.

**Comment by axel-h** [comment]
Could you make a pull request?
