### ISSUE TITLE
delete merged branches

### ISSUE THREAD

**Issue by axel-h** [seL4/util_libs#72]
There are a lot of branches that look as if the work has been merged. Could you remove them here?
* `missing-lincenses`
* `spdx`
* `spdx-syntax`
* `alyons-ppi`
* `kent/fix-style`
* `kent/rockpro64`
* `kent/remove-warning`
* `nomadeel/fdt-fix`

**Comment by lsf37** [comment]
Got it, and deleted them. Also enabled "automatically delete head branches", which should remove PR branches when they are merged. This is supposed to be on everywhere, but I seem to have missed a few.
