### ISSUE TITLE
iMX8MQ-evk eth driver compilation failure

### ISSUE THREAD

**Issue by bvirfollet** [seL4/util_libs#86]
Hi all,

Contrary to what is explained in util_libs/libethdrivers, the inclusion of imx6 platform definitions (util_libs/libethdrivers/src/plat/imx6/uboot/imx-regs.h) is creating compilation errors.

The problem occurs while compiling camkes example picotcp_single_component for imx8mq-evk.
Is the imx8mq-evk ethernet port really supported? Is there a missing commit in the main tree to fix this?
[EthDriver_imx8mq.txt](https://github.com/seL4/util_libs/files/6349660/EthDriver_imx8mq.txt)

From my understanding, it seems that imx-regs.h from uboot should be selectively loaded for imx6 or for imx8m*. Definitions seem really different and should certainly be stored in separated folders, I mean util_libs/libethdrivers/src/plat/imx6 and util_libs/libethdrivers/src/plat/imx8m.

Is it a current action on roadmap? What do you think about it?

**Comment by axel-h** [comment]
You need the first commit from https://bitbucket.hensoldt-cyber.systems/projects/SEOS/repos/sandbox/pull-requests/595/overview, currently this is https://github.com/seL4/util_libs/pull/83/commits/4b3cf7a2031050fccb5472141f96ddc720e32bba but may change whne I rebase it as master moves on.

**Comment by axel-h** [comment]
I've created https://github.com/seL4/util_libs/pull/87 to get this merged quickly

**Comment by axel-h** [comment]
I wonder, could you do  me a favor and test if the patched from https://github.com/seL4/util_libs/pull/87 don't break the i.MX8 support there?
